AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa Skill "Bons Points" - Lambda + DynamoDB

Parameters:
  SkillId:
    Type: String
  LambdaRuntime:
    Type: String
  LambdaHandler:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String

Globals:
  Function:
    Timeout: 10

Resources:

  BonsPointsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BonsPoints
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accountName
          AttributeType: S
      KeySchema:
        - AttributeName: accountName
          KeyType: HASH

  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref CodeBucket
        Key: !Ref CodeKey
        Version: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref BonsPointsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BonsPointsTable
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref SkillId

Outputs:
  SkillEndpoint:
    Description: ARN Lambda
    Value: !GetAtt AlexaSkillFunction.Arn
